name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile         # 👈 Ensures it uses the correct Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/neighborfit-fullstack:latest
